"""Add weekly_available_slots

Revision ID: c34d4fcd6958
Revises: 9ab8577c1934
Create Date: 2025-07-29 18:11:34.909016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34d4fcd6958'
down_revision: Union[str, Sequence[str], None] = '9ab8577c1934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('weekly_available_slots', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'weekly_available_slots')
    # ### end Alembic commands ###
